server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location /build/ {
        try_files $uri =404;
        access_log off;
        expires 1y;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }
}
