name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, pdo_pgsql

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installation des dépendances Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Installation des dépendances NPM
        run: npm install

      - name: Build frontend Vite
        run: npm run build

      - name: Création du fichier .env
        run: cp .env.example .env

      - name: Génération de la clé Laravel
        run: php artisan key:generate

      - name: Exécution des tests
        run: php artisan test
